@startuml 7章練習_ACカレーライス


    title カレーライス作り

    start

    
    :材料を用意する;
        
    :野菜を切る;

    :具材を炒める;


    fork
        :具材を煮込む;

        :ルウを入れる;

        :カレー]
    fork again

        :米をとぐ;

        :米を炊く;

        :ライス]
    end fork

    :盛り付ける;

    :カレーライス]

    stop


@enduml