@startuml 図3-6_オブジェクト図
left to right direction
object "<u>空車リスト2: 空車リスト</u>" as k2 {
日付 = 2023/04/28
}
object "<u>空車リスト1: 空車リスト</u>" as k1 {
日付 = 2023/04/27
}
object "<u>車情報1: 車</u>" as car1 {
管理番号=5
車種 = トヨタ プリウス
貸出料金 = 1日¥15000
}
object "<u>車情報2: 車</u>" as car2 {
管理番号=6
車種 = 日産 リーフ
貸出料金 = 1日¥20000
}
k1 -- car1
k1 -- car2
k2 -- car1
@enduml