@startuml 図3-5_抽象化

    class Animal <<abstract>> {
        ---
+ Walk():void
+ {abstract} eat():int
+ {abstract} cry():void
}
class Dog {
---
+ eat():int
+ cry():void
}
class Cat {
---
+ eat():int
+ cry():void
}
Animal <|-down- Dog
Animal <|-down- Cat

hide Animal circle
@enduml