@startuml 図3-7_貸出管理システムのクラス図.pu
' left to right direction
class "空車リスト" as empty_car {
- 日付 : Date
}
class "車" as car {
- 管理番号:int
- 車種:String
- 貸出料金:int
}
class "貸出" as rental {
- 貸出番号:int
}
class "顧客" as customer {
- 名前: String
- 電話番号:String
- 郵便番号:String
- 住所:String
}
class "予約" as reserve {
- 予約番号: int
- 予約日:Date
}
empty_car "1" o-ri- "*" rental
empty_car "*" o-down- "*" car
rental "0..1" -down- "0..1" reserve
car "1" -ri- "*" reserve
rental "1" -ri- "1" customer
reserve "1" -up- "1" customer
@enduml
