@startuml 図7-10_AC_コンビニで弁当買う

    |客|
    start
    :弁当をレジに持っていく;
    |店員|
    fork
    |客|
    :お金を支払う;
    |店員|
    :清算する;
    fork again
    if (あたためますか) then (Yes)
     :弁当をあたためる;
    else (No)
    endif
    :弁当を袋に入れる;
    end fork 
       |客|
    :弁当を手に持つ;


    stop

    ' |客|
    ' :お金を支払う;

@enduml