@startuml 演習4-2_SD_利用者と予約画面

    hide footbox
    autonumber /'メッセージに自動で番号を降る '/
    skinparam style strictuml /' 厳密なUMLに準拠する '/

    participant "<u>user:利用者</u>" as user

    participant "<u>:予約画面</u>" as reserve

    activate user
        user ->> reserve: ログインメッセージ取得()
        activate reserve
            reserve -> reserve: 認証()
            activate reserve
        deactivate reserve
    deactivate user
@enduml
