@startuml 演習4-6_SD_Web画像検索

    hide footbox
    ' autonumber /'メッセージに自動で番号を降る '/
    skinparam style strictuml /' 厳密なUMLに準拠する '/

    actor "<u>:ユーザ</u>" as user

    participant "<u>:ブラウザ</u>" as browser
    participant "<u>:Webサーバ</u>" as web
    participant "<u>:画像サーバ</u>" as image

    activate user
        user -> browser : リンクボタンを押す
        activate browser
            browser -> web: 画像のファイル名
            activate web
                web -> image: 画像ファイル検索を伝える
                activate image
                    image -> image : 画像ファイルを探す
                    web <- image : 検索結果
                deactivate image
                browser <- web : 画像を閲覧可能状態にする
            deactivate web
            user <- browser : 画像ファイル
        deactivate browser
    deactivate user

@enduml