@startuml 演習7-3_AC_レストランのアクティビティ図

    title レストラン

    |顧客|
    start
    :案内を依頼する;
    |給仕|
    :テーブルに案内する;
    :メニューを渡す;
    :メニュー]

    |顧客|
    :注文を決める;
    |給仕|
    :注文を受ける;
    :注文]
    :料理人に料理を伝える;

    fork
    :伝票を書く;
    :伝票]
    :伝票を渡す;
    fork again
    |料理人|
    :注文を受ける;
    :注文]
    :料理を作る;
    :料理]
    |給仕|
    :料理を運ぶ;
    end fork
    
    |顧客|
    :料理を食べる;
    :代金を支払う;

    stop






    @enduml