
@startuml 演習2-1_UM_出張管理システム.pu
left to right direction
    actor 交通費生産システム #DDDDDD;line:black;line.bold;
    actor 申請者 #DDDDDD;line:black;line.bold;
    actor 承認者 #DDDDDD;line:black;line.bold;
    actor 経理担当者 #DDDDDD;line:black;line.bold;

    rectangle 出張申請システム{
        usecase 出張申請を登録する
        usecase 出張申請を提出する
        usecase 出張申請を承認する
        usecase 出張申請を却下する
        usecase 出張申請を差し戻す
        usecase 出張申請を確認する
    }

    出張申請を登録する <--  交通費生産システム
    申請者 --> 出張申請を提出する
    申請者 --> 出張申請を登録する
    承認者 --> 出張申請を承認する
    承認者 --> 出張申請を却下する
    承認者 --> 出張申請を差し戻す
    承認者 --> 出張申請を確認する
    経理担当者 --> 出張申請を確認する

@enduml