@startuml 演習4-1_SD_ラーメン屋さんでの注文

hide footbox
autonumber /'メッセージに自動で番号を降る '/
skinparam style strictuml /' 厳密なUMLに準拠する '/

actor "<u>:客</u>" as customer

participant "<u>:フロア店員</u>" as clerk
participant "<u>:料理人</u>" as cook

activate customer
    customer -> clerk: ラーメンを注文する
    activate clerk
        clerk -> cook: 調理を指示する
        activate cook
            cook -> cook: 調理をする
        clerk <-- cook: ラーメン
        deactivate cook
    customer <-- clerk: ラーメン 
    deactivate clerk
deactivate customer

@enduml