@startuml 演習7-2_AC_製品を製造するアクティビティ図

    |販売代理店|
    start
    :発注;
    |営業部門|
    :受注;
    :在庫調査;
    if () then (在庫あり)
     :;
     note right
     作図の都合上、
     ダミーの
     アクティビティを
     記述
     end note
  
    else (在庫なし)
     |製造部門|
     :製造;
    endif
    |営業部門| 
    :発送;
    |販売代理店|
    :検収/支払い;
    |営業部門|
    :入金確認;
    stop
@enduml