@startuml 演習3-5_OBJ_ホテル宿泊予約

    left to right direction

     object ホテル {
        部屋
     }
     object "<u>301号室:客室 </u>" as room1 {
        タイプ = シングル
        価格 = 11,000円
        キャンペーン価格 = 9,000円
     }
     object "<u>302号室:客室 </u>" as room2 {
        タイプ = シングル
        価格 = 11,000円
        キャンペーン価格 = 9,000円

     }
     object "<u>303号室:客室 </u>" as room3 {
        タイプ = シングル
        価格 = 11,000円
        キャンペーン価格 = 9,000円
     }
     object "<u>A:利用者</u>" as user1 {
        名前 = Aさん
        住所 = 盛岡市********
        電話番号 = 000-1111
     }
     object "<u>B:利用者</u>" as user2 {
        名前 = Bさん
        住所 = 盛岡市********
        電話番号 = 000-2222
     }
     object 予約 {
        チェックイン日 =  5/3
        滞在期間 = 二泊
        値段 = 18,000円
     }
     ホテル -- room1
     ホテル -- room2
     ホテル -- room3
     room1  -- user1
     room3  -- user2
     user1 -- 予約
     user2 -- 予約
@enduml