@startuml 演習3-3_CL_ホテルと利用者と部屋と予約.pu
 
    left to right direction
    
    class 利用者{
        - 名前
        - 住所
        - 電話番号
    }
    class ホテル{
        - 部屋
    }
    class 予約  {
        - チェックイン日
        - 滞在期間
        - 値段
    }
    class 部屋  {
        - タイプ
        - 価格
        - キャンペーン価格
    }

    ホテル "1"*-- 部屋
    部屋      o-- 利用者
    利用者    o-- 予約
    ホテル    -- 利用者

    @enduml