@startuml 演習6-4-5_ステートマシン図_自動販売機

    ' left to right direction

    [*] -right-> 料金投入待ち
    料金投入待ち -->ボタン選択待ち: お金を入れる
    ボタン選択待ち --> ドリンク排出中: ボタンを押す
    ドリンク排出中 --> 料金投入待ち: ドリンクの排出完了
    料金投入待ち -right-> [*]
    
@enduml