@startuml 演習2-8_UC_ホテル予約システム.pu

    left to right direction

    actor 利用者
    actor 管理者
    actor ホテル従業員

    rectangle ホテル予約システム {
        usecase 空室状況の閲覧
        usecase キャンペーン
        usecase キャンペーン価格
        usecase (<u>予約</u>\n拡張点\nキャンペーン中) as input 
        usecase ログインする
        usecase 会員登録する
        usecase 予約の集計
        usecase 空室状況を入力する
    }

    空室状況の閲覧 <-- 利用者
    利用者 --> 会員登録する
    ホテル従業員 --> 空室状況を入力する
    管理者 --> 予約の集計
    ホテル従業員 <|-- 管理者
    空室状況を入力する ..> ログインする: <<include>>
    予約の集計 ..> ログインする: <<include>>
     input .> キャンペーン価格: <<include>>
    キャンペーン .> input: <<extend>>   
    会員登録する ..> input : <<extend>>
    input ..> ログインする : <<include>>    
@enduml