@startuml 演習6-3_ステートマシン図_診察予約システム

    ' left to right direction

    [*] -right-> メニュー
    メニュー -right-> [*]

    メニュー --> 予約と確認: 予約と確認を押す
    メニュー <-- 予約と確認: 取消を押す
    予約と確認 -right-> あなたの順番: 確認を押す
    予約と確認 -right-> あなたの順番: 登録を押す
    メニュー <--   あなたの順番: メニューへを押す
    メニュー --> 今の順番: 今の順番を押す
    メニュー <-- 今の順番: メニューへを押す
@enduml